/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.AppInfo;

class ApplicationGetPublicInfoResponse {
    private AppInfo value;

    public void setValue(AppInfo value) {
        this.value = value;
    }

    public AppInfo getValue() {
        return this.value;
    }

    public String toXML() {
        return "<application_getPublicInfo_response>" + this.value + "</application_getPublicInfo_response>";
    }
}