/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.SessionKey;

class AuthRenewOfflineSessionResponse {
    private SessionKey value;

    public void setValue(SessionKey value) {
        this.value = value;
    }

    public SessionKey getValue() {
        return this.value;
    }

    public String toXML() {
        return "<auth_renewOfflineSession_response>" + this.value + "</auth_renewOfflineSession_response>";
    }
}