/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.SessionSecret;

class AuthPromoteSessionResponse {
    private SessionSecret value;

    public void setValue(SessionSecret value) {
        this.value = value;
    }

    public SessionSecret getValue() {
        return this.value;
    }

    public String toXML() {
        return "<auth_promoteSession_response>" + this.value + "</auth_promoteSession_response>";
    }
}