/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.PublicSessionData;

class AuthGetSignedPublicSessionDataResponse {
    private PublicSessionData value;

    public void setValue(PublicSessionData value) {
        this.value = value;
    }

    public PublicSessionData getValue() {
        return this.value;
    }

    public String toXML() {
        return "<auth_getSignedPublicSessionData_response>" + this.value + "</auth_getSignedPublicSessionData_response>";
    }
}