/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.Fbid;

class DashboardNews  {


    private String image;
    private Fbid fbid;
    private Integer time;


    public void setImage(String image) {
        this.image = image;
    }

    public String getImage() {
        return this.image;
    }
    public void setFbid(Fbid fbid) {
        this.fbid = fbid;
    }

    public Fbid getFbid() {
        return this.fbid;
    }
    public void setTime(Integer time) {
        this.time = time;
    }

    public Integer getTime() {
        return this.time;
    }

    public String toXML() {
        return "<image>" + this.image + "</image>" + this.fbid.toXML() + "<time>" + this.time + "</time>";
    }
}