/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.ObjectAssocInfo;

class DataGetAssociationDefinitionResponse {
    private ObjectAssocInfo value;

    public void setValue(ObjectAssocInfo value) {
        this.value = value;
    }

    public ObjectAssocInfo getValue() {
        return this.value;
    }

    public String toXML() {
        return "<data_getAssociationDefinition_response>" + this.value + "</data_getAssociationDefinition_response>";
    }
}