/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.TemplateBundle;

class FeedGetRegisteredTemplateBundleByIDResponse {
    private TemplateBundle value;

    public void setValue(TemplateBundle value) {
        this.value = value;
    }

    public TemplateBundle getValue() {
        return this.value;
    }

    public String toXML() {
        return "<feed_getRegisteredTemplateBundleByID_response>" + this.value + "</feed_getRegisteredTemplateBundleByID_response>";
    }
}