/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;


class FqlResult  {


    private String name;
    private String fql_result_set;


    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }
    public void setFqlResultSet(String fql_result_set) {
        this.fql_result_set = fql_result_set;
    }

    public String getFqlResultSet() {
        return this.fql_result_set;
    }

    public String toXML() {
        return "<name>" + this.name + "</name>" + "<fql_result_set>" + this.fql_result_set + "</fql_result_set>";
    }
}