/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.Friendlist;

class FriendsCreateListResponse {
    private Friendlist value;

    public void setValue(Friendlist value) {
        this.value = value;
    }

    public Friendlist getValue() {
        return this.value;
    }

    public String toXML() {
        return "<friends_createList_response>" + this.value + "</friends_createList_response>";
    }
}