/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.Uid;
import com.facebook.api.Gid;

class GroupMember  {


    private Uid uid;
    private Gid gid;


    public void setUid(Uid uid) {
        this.uid = uid;
    }

    public Uid getUid() {
        return this.uid;
    }
    public void setGid(Gid gid) {
        this.gid = gid;
    }

    public Gid getGid() {
        return this.gid;
    }

    public String toXML() {
        return this.uid.toXML() + this.gid.toXML();
    }
}