/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;


class InfoField  {


    private String field;


    public void setField(String field) {
        this.field = field;
    }

    public String getField() {
        return this.field;
    }

    public String toXML() {
        return "<field>" + this.field + "</field>";
    }
}