/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.StreamAttachment;

class LinksPreviewResponse {
    private StreamAttachment value;

    public void setValue(StreamAttachment value) {
        this.value = value;
    }

    public StreamAttachment getValue() {
        return this.value;
    }

    public String toXML() {
        return "<links_preview_response>" + this.value + "</links_preview_response>";
    }
}