/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;


class LocaleString  {


    private String native_string;


    public void setNativeString(String native_string) {
        this.native_string = native_string;
    }

    public String getNativeString() {
        return this.native_string;
    }

    public String toXML() {
        return "<native_string>" + this.native_string + "</native_string>";
    }
}