/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.ThreadId;

class MessageCreateThreadResponse {
    private ThreadId value;

    public void setValue(ThreadId value) {
        this.value = value;
    }

    public ThreadId getValue() {
        return this.value;
    }

    public String toXML() {
        return "<message_createThread_response>" + this.value + "</message_createThread_response>";
    }
}