/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.MessageId;

class MessageReplyToThreadResponse {
    private MessageId value;

    public void setValue(MessageId value) {
        this.value = value;
    }

    public MessageId getValue() {
        return this.value;
    }

    public String toXML() {
        return "<message_replyToThread_response>" + this.value + "</message_replyToThread_response>";
    }
}