/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.MessageId;
import com.facebook.api.Uid;
import com.facebook.api.StreamAttachment;
import com.facebook.api.Time;

class Message  {


    private MessageId message_id;
    private Uid author_id;
    private String body;
    private Time created_time;
    private StreamAttachment attachment;


    public void setMessageId(MessageId message_id) {
        this.message_id = message_id;
    }

    public MessageId getMessageId() {
        return this.message_id;
    }
    public void setAuthorId(Uid author_id) {
        this.author_id = author_id;
    }

    public Uid getAuthorId() {
        return this.author_id;
    }
    public void setBody(String body) {
        this.body = body;
    }

    public String getBody() {
        return this.body;
    }
    public void setCreatedTime(Time created_time) {
        this.created_time = created_time;
    }

    public Time getCreatedTime() {
        return this.created_time;
    }
    public void setAttachment(StreamAttachment attachment) {
        this.attachment = attachment;
    }

    public StreamAttachment getAttachment() {
        return this.attachment;
    }

    public String toXML() {
        return this.message_id.toXML() + this.author_id.toXML() + "<body>" + this.body + "</body>" + this.created_time.toXML() + this.attachment.toXML();
    }
}