/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.NoteId;

class NotesCreateResponse {
    private NoteId value;

    public void setValue(NoteId value) {
        this.value = value;
    }

    public NoteId getValue() {
        return this.value;
    }

    public String toXML() {
        return "<notes_create_response>" + this.value + "</notes_create_response>";
    }
}