/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.Time;

class NotificationCount  {


    private Integer unread;
    private Time most_recent;


    public void setUnread(Integer unread) {
        this.unread = unread;
    }

    public Integer getUnread() {
        return this.unread;
    }
    public void setMostRecent(Time most_recent) {
        this.most_recent = most_recent;
    }

    public Time getMostRecent() {
        return this.most_recent;
    }

    public String toXML() {
        return "<unread>" + this.unread + "</unread>" + this.most_recent.toXML();
    }
}