/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.NotificationData;

class NotificationsGetListResponse {
    private NotificationData value;

    public void setValue(NotificationData value) {
        this.value = value;
    }

    public NotificationData getValue() {
        return this.value;
    }

    public String toXML() {
        return "<notifications_getList_response>" + this.value + "</notifications_getList_response>";
    }
}