/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.PageId;
import com.facebook.api.Uid;

class PageFan  {


    private PageId page_id;
    private Uid uid;
    private String type;


    public void setPageId(PageId page_id) {
        this.page_id = page_id;
    }

    public PageId getPageId() {
        return this.page_id;
    }
    public void setUid(Uid uid) {
        this.uid = uid;
    }

    public Uid getUid() {
        return this.uid;
    }
    public void setType(String type) {
        this.type = type;
    }

    public String getType() {
        return this.type;
    }

    public String toXML() {
        return this.page_id.toXML() + this.uid.toXML() + "<type>" + this.type + "</type>";
    }
}