/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.Photo;

class PhotosUploadResponse {
    private Photo value;

    public void setValue(Photo value) {
        this.value = value;
    }

    public Photo getValue() {
        return this.value;
    }

    public String toXML() {
        return "<photos_upload_response>" + this.value + "</photos_upload_response>";
    }
}