/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.Album;

class PhotosCreateAlbumResponse {
    private Album value;

    public void setValue(Album value) {
        this.value = value;
    }

    public Album getValue() {
        return this.value;
    }

    public String toXML() {
        return "<photos_createAlbum_response>" + this.value + "</photos_createAlbum_response>";
    }
}