/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;


class Phrase  {


    private String description;
    private String text;


    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return this.description;
    }
    public void setText(String text) {
        this.text = text;
    }

    public String getText() {
        return this.text;
    }

    public String toXML() {
        return "<description>" + this.description + "</description>" + "<text>" + this.text + "</text>";
    }
}