/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;


class Privacy  {


    private String description;
    private String value;
    private String friends;


    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return this.description;
    }
    public void setValue(String value) {
        this.value = value;
    }

    public String getValue() {
        return this.value;
    }
    public void setFriends(String friends) {
        this.friends = friends;
    }

    public String getFriends() {
        return this.friends;
    }

    public String toXML() {
        return "<description>" + this.description + "</description>" + "<value>" + this.value + "</value>" + "<friends>" + this.friends + "</friends>";
    }
}