/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.Privacy;

class PrivacyGetResponse {
    private Privacy value;

    public void setValue(Privacy value) {
        this.value = value;
    }

    public Privacy getValue() {
        return this.value;
    }

    public String toXML() {
        return "<privacy_get_response>" + this.value + "</privacy_get_response>";
    }
}