/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;


class ShortStoryTemplate  {


    private String template_title;
    private String template_body;


    public void setTemplateTitle(String template_title) {
        this.template_title = template_title;
    }

    public String getTemplateTitle() {
        return this.template_title;
    }
    public void setTemplateBody(String template_body) {
        this.template_body = template_body;
    }

    public String getTemplateBody() {
        return this.template_body;
    }

    public String toXML() {
        return "<template_title>" + this.template_title + "</template_title>" + "<template_body>" + this.template_body + "</template_body>";
    }
}