/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;


class StreamAppData  {


    private Long tbid;
    private String attachment_data;
    private String images;


    public void setTbid(Long tbid) {
        this.tbid = tbid;
    }

    public Long getTbid() {
        return this.tbid;
    }
    public void setAttachmentData(String attachment_data) {
        this.attachment_data = attachment_data;
    }

    public String getAttachmentData() {
        return this.attachment_data;
    }
    public void setImages(String images) {
        this.images = images;
    }

    public String getImages() {
        return this.images;
    }

    public String toXML() {
        return "<tbid>" + this.tbid + "</tbid>" + "<attachment_data>" + this.attachment_data + "</attachment_data>" + "<images>" + this.images + "</images>";
    }
}