/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;


class TranslationInfo  {


    private String translation;
    private String status;
    private String description;


    public void setTranslation(String translation) {
        this.translation = translation;
    }

    public String getTranslation() {
        return this.translation;
    }
    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatus() {
        return this.status;
    }
    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return this.description;
    }

    public String toXML() {
        return "<translation>" + this.translation + "</translation>" + "<status>" + this.status + "</status>" + "<description>" + this.description + "</description>";
    }
}