/**
 * This code was generated by the xsdtocls codegenerator and is not intended to be changed manually!
 * Note that all your changes will be lost if the codegenerator runs another time on the same destination directory!
 * For further information take a look at: https://github.com/KLINGTdotNET/ssf_project
 */

package com.facebook.api;

import com.facebook.api.Video;

class VideoUploadResponse {
    private Video value;

    public void setValue(Video value) {
        this.value = value;
    }

    public Video getValue() {
        return this.value;
    }

    public String toXML() {
        return "<video_upload_response>" + this.value + "</video_upload_response>";
    }
}